# Generated by Django 4.2.16 on 2026-03-20 18:44

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceList',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
                ('description', models.TextField(blank=True, verbose_name='Descrição')),
                ('global_discount_pct', models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Desconto global (%)')),
                ('valid_from', models.DateField(blank=True, null=True, verbose_name='Válida de')),
                ('valid_until', models.DateField(blank=True, null=True, verbose_name='Válida até')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativa')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Tabela de preços',
                'verbose_name_plural': 'Tabelas de preços',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PromoCode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=30, unique=True, verbose_name='Código')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='Descrição')),
                ('discount_type', models.CharField(choices=[('percentage', 'Percentual (%)'), ('fixed', 'Valor fixo (R$)'), ('free_shipping', 'Frete grátis')], default='percentage', max_length=20, verbose_name='Tipo de desconto')),
                ('discount_value', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Valor do desconto')),
                ('min_order_value', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Pedido mínimo (R$)')),
                ('max_uses', models.PositiveIntegerField(blank=True, null=True, verbose_name='Máximo de usos')),
                ('uses_count', models.PositiveIntegerField(default=0, verbose_name='Usos realizados')),
                ('valid_from', models.DateTimeField(blank=True, null=True, verbose_name='Válido de')),
                ('valid_until', models.DateTimeField(blank=True, null=True, verbose_name='Válido até')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.category', verbose_name='Restrito à categoria')),
            ],
            options={
                'verbose_name': 'Código promocional',
                'verbose_name_plural': 'Códigos promocionais',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PriceListItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Preço')),
                ('price_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='pricing.pricelist', verbose_name='Tabela')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_list_items', to='catalog.product', verbose_name='Produto')),
            ],
            options={
                'verbose_name': 'Item da tabela',
                'verbose_name_plural': 'Itens da tabela',
                'unique_together': {('price_list', 'product')},
            },
        ),
    ]
