# Generated by Django 4.2.16 on 2026-03-20 18:44

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0001_initial'),
        ('pricing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order_number', models.CharField(blank=True, max_length=20, unique=True, verbose_name='Número do pedido')),
                ('status', models.CharField(choices=[('draft', 'Rascunho'), ('pending_payment', 'Aguardando pagamento'), ('paid', 'Pago'), ('invoiced', 'Faturado (NF-e emitida)'), ('shipped', 'Enviado'), ('delivered', 'Entregue'), ('cancelled', 'Cancelado')], default='pending_payment', max_length=20, verbose_name='Status')),
                ('payment_method', models.CharField(blank=True, choices=[('pix', 'Pix'), ('boleto', 'Boleto Bancário'), ('credit_card', 'Cartão de crédito'), ('bank_transfer', 'Transferência bancária')], max_length=20, verbose_name='Forma de pagamento')),
                ('discount_pct', models.DecimalField(decimal_places=1, default=0, max_digits=4, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(20)], verbose_name='Desconto (%)')),
                ('discount_note', models.CharField(blank=True, max_length=200, verbose_name='Motivo do desconto')),
                ('promo_discount_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Desconto promo (R$)')),
                ('delivery_cep', models.CharField(blank=True, max_length=9, verbose_name='CEP de entrega')),
                ('delivery_street', models.CharField(blank=True, max_length=255, verbose_name='Logradouro')),
                ('delivery_number', models.CharField(blank=True, max_length=20, verbose_name='Número')),
                ('delivery_complement', models.CharField(blank=True, max_length=100, verbose_name='Complemento')),
                ('delivery_neighborhood', models.CharField(blank=True, max_length=100, verbose_name='Bairro')),
                ('delivery_city', models.CharField(blank=True, max_length=100, verbose_name='Cidade')),
                ('delivery_state', models.CharField(blank=True, max_length=2, verbose_name='UF')),
                ('freight_cost', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Frete (R$)')),
                ('mp_preference_id', models.CharField(blank=True, max_length=100, verbose_name='MP Preference ID')),
                ('mp_payment_id', models.CharField(blank=True, max_length=100, verbose_name='MP Payment ID')),
                ('payment_link', models.URLField(blank=True, verbose_name='Link de pagamento')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='Pago em')),
                ('nfe_key', models.CharField(blank=True, max_length=50, verbose_name='Chave NF-e')),
                ('nfe_pdf_url', models.URLField(blank=True, verbose_name='PDF NF-e')),
                ('nfe_xml_url', models.URLField(blank=True, verbose_name='XML NF-e')),
                ('nfe_status', models.CharField(blank=True, choices=[('pending', 'Pendente'), ('processing', 'Processando'), ('authorized', 'Autorizada'), ('error', 'Erro')], max_length=20, verbose_name='Status NF-e')),
                ('nfe_emitted_at', models.DateTimeField(blank=True, null=True, verbose_name='NF-e emitida em')),
                ('tracking_code', models.CharField(blank=True, max_length=50, verbose_name='Código de rastreio')),
                ('shipped_at', models.DateTimeField(blank=True, null=True, verbose_name='Enviado em')),
                ('delivered_at', models.DateTimeField(blank=True, null=True, verbose_name='Entregue em')),
                ('internal_notes', models.TextField(blank=True, verbose_name='Notas internas')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('discount_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='discounts_given', to=settings.AUTH_USER_MODEL, verbose_name='Desconto aplicado por')),
                ('on_behalf_of', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='accounts.company', verbose_name='Cliente')),
                ('placed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='placed_orders', to=settings.AUTH_USER_MODEL, verbose_name='Colocado por')),
                ('promo_code', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='pricing.promocode', verbose_name='Código promocional')),
            ],
            options={
                'verbose_name': 'Pedido',
                'verbose_name_plural': 'Pedidos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Quantidade')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Preço unitário (no momento da venda)')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order', verbose_name='Pedido')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_items', to='catalog.product', verbose_name='Produto')),
            ],
            options={
                'verbose_name': 'Item do pedido',
                'verbose_name_plural': 'Itens do pedido',
            },
        ),
    ]
