# Generated by Django 4.2.16 on 2026-03-20 18:44

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NFeEmission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('processing', 'Processando'), ('authorized', 'Autorizada'), ('error', 'Erro'), ('cancelled', 'Cancelada')], default='pending', max_length=20, verbose_name='Status')),
                ('focus_nfe_ref', models.CharField(blank=True, max_length=100, verbose_name='Referência Focus NFe')),
                ('access_key', models.CharField(blank=True, max_length=50, verbose_name='Chave de acesso')),
                ('pdf_url', models.URLField(blank=True, verbose_name='PDF')),
                ('xml_url', models.URLField(blank=True, verbose_name='XML')),
                ('error_message', models.TextField(blank=True, verbose_name='Erro')),
                ('attempts', models.PositiveIntegerField(default=0, verbose_name='Tentativas')),
                ('emitted_at', models.DateTimeField(blank=True, null=True, verbose_name='Emitida em')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='nfe_emission', to='orders.order', verbose_name='Pedido')),
            ],
            options={
                'verbose_name': 'Emissão NF-e',
                'verbose_name_plural': 'Emissões NF-e',
                'ordering': ['-created_at'],
            },
        ),
    ]
