# Generated by Django 4.2.16 on 2026-03-20 18:44

import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
                ('slug', models.SlugField(max_length=120, unique=True)),
                ('description', models.TextField(blank=True, verbose_name='Descrição')),
                ('image', models.ImageField(blank=True, null=True, upload_to='categories/', verbose_name='Imagem')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Ordem')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativa')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='catalog.category', verbose_name='Categoria pai')),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sku', models.CharField(max_length=64, unique=True, verbose_name='SKU')),
                ('name', models.CharField(max_length=255, verbose_name='Nome')),
                ('slug', models.SlugField(max_length=280, unique=True)),
                ('description', models.TextField(blank=True, verbose_name='Descrição')),
                ('base_price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Preço base')),
                ('unit', models.CharField(default='un', max_length=20, verbose_name='Unidade')),
                ('ncm_code', models.CharField(max_length=10, verbose_name='NCM')),
                ('cest_code', models.CharField(blank=True, max_length=9, verbose_name='CEST')),
                ('stock_qty', models.IntegerField(default=0, verbose_name='Estoque')),
                ('min_stock_alert', models.IntegerField(default=5, verbose_name='Alerta estoque mínimo')),
                ('weight_kg', models.DecimalField(decimal_places=3, default=0, max_digits=8, verbose_name='Peso (kg)')),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='Imagem principal')),
                ('image_url', models.URLField(blank=True, verbose_name='URL da imagem')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Destaque')),
                ('search_vector', django.contrib.postgres.search.SearchVectorField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='catalog.category', verbose_name='Categoria')),
            ],
            options={
                'verbose_name': 'Produto',
                'verbose_name_plural': 'Produtos',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PartCompatibility',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('equipment_brand', models.CharField(max_length=100, verbose_name='Marca do equipamento')),
                ('equipment_model', models.CharField(max_length=200, verbose_name='Modelo do equipamento')),
                ('year_from', models.PositiveIntegerField(blank=True, null=True, verbose_name='Ano (de)')),
                ('year_to', models.PositiveIntegerField(blank=True, null=True, verbose_name='Ano (até)')),
                ('notes', models.CharField(blank=True, max_length=255, verbose_name='Observações')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compatibilities', to='catalog.product', verbose_name='Produto')),
            ],
            options={
                'verbose_name': 'Compatibilidade',
                'verbose_name_plural': 'Compatibilidades',
                'ordering': ['equipment_brand', 'equipment_model'],
            },
        ),
        migrations.AddIndex(
            model_name='product',
            index=django.contrib.postgres.indexes.GinIndex(fields=['search_vector'], name='catalog_pro_search__6e8905_gin'),
        ),
    ]
