# Generated by Django 4.2.16 on 2026-03-20 18:44

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pricing', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cnpj', models.CharField(max_length=18, unique=True, verbose_name='CNPJ')),
                ('razao_social', models.CharField(max_length=255, verbose_name='Razão Social')),
                ('nome_fantasia', models.CharField(blank=True, max_length=255, verbose_name='Nome Fantasia')),
                ('tier', models.CharField(choices=[('consumidor', 'Consumidor Final'), ('revendedor', 'Revendedor'), ('distribuidor', 'Distribuidor')], default='consumidor', max_length=20, verbose_name='Tier')),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('cep', models.CharField(blank=True, max_length=9, verbose_name='CEP')),
                ('street', models.CharField(blank=True, max_length=255, verbose_name='Logradouro')),
                ('number', models.CharField(blank=True, max_length=20, verbose_name='Número')),
                ('complement', models.CharField(blank=True, max_length=100, verbose_name='Complemento')),
                ('neighborhood', models.CharField(blank=True, max_length=100, verbose_name='Bairro')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='Cidade')),
                ('state', models.CharField(blank=True, max_length=2, verbose_name='UF')),
                ('ie', models.CharField(blank=True, max_length=30, verbose_name='Inscrição Estadual')),
                ('is_mei', models.BooleanField(default=False, verbose_name='MEI')),
                ('credit_limit', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Limite de crédito')),
                ('payment_terms', models.CharField(choices=[('immediate', 'À vista'), ('net_30', '30 dias'), ('net_60', '60 dias'), ('net_90', '90 dias')], default='immediate', max_length=20, verbose_name='Prazo de pagamento')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('price_list', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='companies', to='pricing.pricelist', verbose_name='Tabela de preços')),
            ],
            options={
                'verbose_name': 'Empresa',
                'verbose_name_plural': 'Empresas',
                'ordering': ['razao_social'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='E-mail')),
                ('full_name', models.CharField(max_length=255, verbose_name='Nome completo')),
                ('role', models.CharField(choices=[('admin', 'Administrador'), ('salesman', 'Vendedor'), ('client', 'Cliente')], default='client', max_length=20, verbose_name='Perfil')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Telefone')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('is_staff', models.BooleanField(default=False, verbose_name='Staff')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_companies', models.ManyToManyField(blank=True, related_name='salesmen', to='accounts.company', verbose_name='Clientes atribuídos')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='accounts.company', verbose_name='Empresa')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Usuário',
                'verbose_name_plural': 'Usuários',
                'ordering': ['full_name'],
            },
        ),
    ]
